#!/bin/bash
#Menu Adaptado Base ADM

#Donwload
wget -O /bin/usercodes https://www.dropbox.com/s/h2qtcd5to8m4g8i/usercodes > /dev/null 2>&1
wget -O /bin/gestorcodes https://www.dropbox.com/s/h2msl5636khqd93/gestorcodes > /dev/null 2>&1
wget -O /bin/ferramentascodes https://www.dropbox.com/s/zfq6rq9sp4y3y2c/ferramentascodes > /dev/null 2>&1
wget -O /bin/menu https://www.dropbox.com/s/d3pdfvz6vtgk09t/menu > /dev/null 2>&1

#Permisos
chmod +x /bin/usercodes
chmod +x /bin/ferramentascodes
chmod +x /bin/gestorcodes
chmod +x /bin/menu

#Ejecucion
/bin/menu

#fim